### ISSUE TITLE
TypeError: prepare_job_execution() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by sandeepsn1997** [michaelbrooks/rq-win#10] opened 2021-07-06 11:42 UTC
Traceback (most recent call last):
  File "e:\miniconda\envs\ziva_3.0\lib\site-packages\rq\worker.py", line 599, in work
    self.execute_job(job, queue)
  File "e:\miniconda\envs\ziva_3.0\lib\site-packages\rq_win\worker.py", line 61, in execute_job
    self.main_work_horse(job, queue)
  File "e:\miniconda\envs\ziva_3.0\lib\site-packages\rq_win\worker.py", line 71, in main_work_horse
    success = self.perform_job(job, queue)
  File "e:\miniconda\envs\ziva_3.0\lib\site-packages\rq_win\worker.py", line 79, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
TypeError: prepare_job_execution() takes 2 positional arguments but 3 were given

getting this error, please respond.

**Comment by michaelbrooks** [comment] 2021-07-06 18:43
Looks like a duplicate of https://github.com/michaelbrooks/rq-win/issues/9

**Closed by michaelbrooks** 2021-07-06 18:43 UTC
